### ISSUE TITLE
[vote]Nebula Hackathon 2021 The Most Popular Project ｜ Nebula 黑客马拉松社区人气奖

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula-community#38]
Please select your favorite participating teams and project in this issue'comment, and send yours 👍 as vote.

The Nebula staff will count 👍 of each team on 2021.12.26 12:00 UTC+8, and the team has maximum number
win The Most Popular Project Award. The winning team win a cash prize of $ 3,000.

If you are a participating team, you can refer to the following format to comment issue and generate your voting items, format: team name + project name + a short project introduction.

About activity infos: [https://nebula-graph.io/hackathon/](https://nebula-graph.io/hackathon/)

请在本 issue comment 中选择你所喜欢的项目及参赛队伍，送出你的 👍 作为投票。

Nebula Hackathon 活动组将在 2021.12.26 中午统计各个队伍所得赞，获得最多赞票的队伍为本次社区人气奖，获得 ¥ 20,000 现金大奖。

如果你是参赛队伍，可参照以下格式来 comment 生成你的队伍投票项，格式：队名 + 项目名 + 一句话项目介绍

更多活动详情参见：[https://nebula-graph.com.cn/hackathon/](https://nebula-graph.com.cn/hackathon/)

**Comment by frank-zsy** [comment]
队名：源光闪烁
项目名：OpenGalaxy
项目介绍：开源协作世界色彩缤纷，数千万的开发者和项目通过一次次的 Issue 和 PR 关联在了一起，构成了一个巨大的开源协作网络，我们希望通过将这个协作网络通过图数据库构建描述。并通过算法来探索这个开源世界，最终为大家呈现出一个真正的开源星系——OpenGalaxy。

Team name: Allumos
Project name: OpenGalaxy
Project introduction: The open source world is composed of millions of developers and projects by all the contributions like issues and PRs. We will use open source data to construct the collaborate network on GitHub and use graph algorithm to look into it. Finally we will present the whole open source world to you which is OpenGalaxy.

**Comment by heyanlong** [comment]
队名：NullReferenceException
项目名：nebula-net & nebula-php
项目介绍：From now on, we can import Nebula Graph in .NET & PHP.

Team name：NullReferenceException
Project name：nebula-net & nebula-php
Project introduction：From now on, we can import Nebula Graph in .NET & PHP.

**Comment by knwng** [comment]
队名：Alice, Bob and Ciri
项目名：ppgi
项目介绍：利用隐私计算技术，实现隐私保护下的图数据合并
团队成员：
- @knwng
- @zilinzhu

Team Name: Alice, Bob and Ciri
Project Name: ppgi
Project Introduction: Implement privacy-preserving graph intersection.
Team Members:
- @knwng
- @zilinzhu

**Comment by logan8128** [comment]
队名：Winter is Coming
项目名：raft优化
项目介绍：进行nebula-storage raft的优化
团队成员：

[@logan8128](https://github.com/logan8128)
Team Name: Winter is Coming
Project Name: raft optimization
Project Introduction: raft optimization
Team Members:

[@logan8128](https://github.com/logan8128)

**Comment by hao-go** [comment]
队名：智联
项目名：数控机床设计选型知识库构建
项目介绍：构建知识图谱可以将数控机床领域碎片化的数据信息有机整合，提升为具备系统、严谨结构的数控机床知识库，用户基于此可查询学习数控机床领域知识概念，还可以推理某些潜在的知识，从而拓展用户的知识面和理解深度。
团队成员：
@hao-go
Team name: WisdomTogether
Project name: Research and development of knowledge base system in design of CNC machine tools
Project introduction:The construction of knowledge atlas can organically integrate the fragmented data information in the field of NC machine tools and promote it into a NC machine tool knowledge base with a systematic and rigorous structure. Based on this, users can query and learn the knowledge concepts in the field of NC machine tools and infer some potential knowledge, so as to expand users' knowledge and understanding depth.
Team Members:
@hao-go

**Comment by aaron-zzh** [comment]
队名：学记智能
项目名：学记助理
项目介绍：基于统一语义，在一个轻量文档上，与专属智能助理一起构建知识地图，积累你的知识财富！
团队成员：
 @aaron-zzh —— 产品设计、应用开发
@队员招募中 ——

**Comment by Reid00** [comment]
队名: node_module
项目名: nebula-node
项目介绍：Nebula node.js 客户端
成员:
- @Reid00
- @wujjpp

项目地址:  [nebula-node](https://github.com/vesoft-inc/nebula-node)

Team Name: node_module
Project Name: nebula-node
Project Introduction: nebula node.js client
Team Members:

- @Reid00
- @wujjpp

Project URL: [nebula-node](https://github.com/vesoft-inc/nebula-node)

**Comment by Reminiscent** [comment]
队名：咕咕咕
项目名：Index Advisor
项目介绍：可以推荐去增加或删除索引
团队成员：
@Reminiscent

**Comment by QingZ11** [comment]
> 队名：咕咕咕 项目名：Index Advisor 项目介绍：可以推荐去增加或删除索引 团队成员： @Reminiscent

Hi，我看到了你的队伍信息，但没收到你的报名信息，🤔 记得在 12.13 之前报名哈，报名传送[https://wj.qq.com/s2/9279045/480f/](https://wj.qq.com/s2/9279045/480f/)

**Comment by eatguava** [comment]
队名：卡魔拉
项目名：Gamora
项目简介：把 Nebula Graph 改造成分布式强一致性持久型 Redis。目前开源社区基于 Redis 协议的持久型KV存储基本上都不具备集群模式，比如 ssdb 或者 pika，难以支撑超大容量的存储需求。本项目致力于提供一个可供现有 Redis client 访问的强一致性分布式KV存储，支持 string, list, set, sorted set, map 等 Redis 数据结构。

**Comment by 1uvu** [comment]
队名：Rise
项目名：基于终端的数据库信息收集与诊断工具
项目介绍：支持监控和收集多个数据库节点的物理信息和服务信息，并给出信息诊断结果。
功能概括为如下：
● 指定单一/多个节点获取当前物理信息和服务信息, 输出到命令行或文件
● 指定单一/多个节点监控历史物理信息和服务信息, 输出到命令行或文件
● 根据以上分析得出诊断结果

**Comment by baronbigghf** [comment]
队名：喵星人与汪星人
项目名称：图谱推荐引擎
项目介绍：通过知识图谱的信息和用户的行为数据，挖掘用户感兴趣的内容或商品，推荐给用户。
例如：你在盒马生鲜买了一只龙虾，盒马生鲜就会推荐各种关于龙虾的做法，以及每种做法需要买的食材。如果你对其中一种做法感兴趣，就可以直接下单购买食材和配料。这样做法有了，食材也有了，你会觉得这种购物体验非常周到。

**Comment by jackhackson** [comment]
队名：AI-COM
项目名：零售行为发现
项目介绍：采用nebula代替传统数据库对零售商业行为进行智能发现
团队成员：
       @梅影零落:--计算数学大三学生

Team Name: AI-COM
Project Name: Retail behavior discovery
Project Introduction:Using Nebula instead of traditional database to discover retail business behavior intelligently
Team Members:
      @Michael--- junior students of Computational Mathematics

**Comment by tageecc** [comment]
队名：非常完美队
项目名：nebula-terminal-dashboard
项目介绍：基于nebula-stats-exporter 的terminal 版运维监控工具
团队成员：张早，璟页，张泽旋

**Comment by critical27** [comment]
队伍：大油条东北虎
项目名：如何吊打nebula的深度查询
项目介绍：性能优化尝试，看看是吊打还是被吊打
团队成员： @liuyu85cn @liwenhui-soul @pengweisong @critical27

**Comment by arcosx** [comment]
队伍：星云之巅
项目名：UDF Enhanced Nebula
项目介绍(WIP)：基于 Wasm 实现 Nebula 用户自定义函数。
团队成员：@arcosx @Triple-Z

**Comment by ModestYjx** [comment]
队名：平岸科技
项目名：“MAgriculture”--基于Nebula的计算机智能辅助草莓采摘农业旅游解决方案
项目介绍：近年来，草莓采摘旅游进入到了人们的视野。通过设计一款基于人工智能的软件实现草莓成熟度检测、农作物知识普及与数字化农业管理，确保游客尽快采摘到成熟度最高的草莓，普及中小学生农村经验教育，并能提高游客游玩体验，节省农场主人力雇佣成本。
成员：

@ModestYjx - 北京大学 & 研究生

小程序体验地址：
![](/uploads/upload_013695f549c528739a421a955297e7ce.png)


Team name: Ping'an Technology
Project Name: "magriculture" -- agricultural tourism solution for computer-aided strawberry picking based on Nebula
Project introduction: in recent years, strawberry picking tourism has entered people's vision. Through the design of a software based on artificial intelligence, strawberry maturity detection, crop knowledge popularization and digital agricultural management are realized to ensure that tourists pick the strawberries with the highest maturity as soon as possible, popularize rural experience education for primary and secondary school students, improve tourists' play experience and save the employment cost of farm owners.
Members:
@Modestyjx - Peking University &amp; Graduate
Applet experience address:
![](/uploads/upload_013695f549c528739a421a955297e7ce.png)

**Comment by wenhaocs** [comment]
队名：M42
项目名：Fly to M78
项目介绍：
目前Nebula无论在OLTP还是OLAP场景下都存在比较明显的性能问题。其原因存在于多个方面，包含底层的存储引擎，整体架构，以及Nebula不同layer。我们目标通过对Nebula的整体架构以及不同layer进行优化来提升Nebula的TP和AP性能，包括Nebula存储引擎RocksDB的优化，caching等。

成员：

@wenhaocs  - Nebula SWE
@nevermore3 - Nebula  SWE

Team name: M42
Project name: Fly to M78
Project introduction: The Nebula performance is suffering in both OLTP and OLAP for a period of time. The reason is complicated and multi-factored. The underlying storage engine, overall architecture, different layers of Nebula all contribute to the performance issues. The goal of this project is to improve the OLTP and OLAT performance of Nebula by adjusting and optimizing the architecture and different layers. This may include RocksDB optimization, caching, etc.

@wenhaocs 
@nevermore3

**Comment by Shihao-Zhong** [comment]
队名：other side
项目名：分布式追踪和可观测性在nebula grpah的实现
项目介绍：
目前Nebula只通过http提供有限的metric，目前仅包括心跳包延迟，点/边操作延迟和一些慢查询延迟，说白了还是旧式的machine-centric-tracing，本项目的目标是使用opentlemetry对nebulagraph做全链路的workflow-centric-tracing。如果说machine-centric-tracing是以模块为单位的垂直监控，而workflow-centric-tracing则是以请求为单位的水平监控，通过workflow-centric-tracing，我们可以获得更细致的全链路系统状况，从而得知慢SQL到底慢在哪一步，可以通过哪些方式优化。

成员
@Shihao-Zhong
@WPH95

**Comment by MMyheart** [comment]
队名：图学习兴趣小队
项目名：Euler Based on NebulaGraph
项目介绍：NebulaGraph替换Euler2原生的内存图引擎，让图数据库的用户可以低成本的尝试图学习能力。
团队成员：
@MMyheart
@liang-Q8797
@charlygao
@LuconYang

**Comment by wey-gu** [comment]
队名：Marauders
项目名：活点地图
项目介绍：一个Nebula后端驱动的源数据管理、数据血缘的 PoC
团队成员：
@wey-gu 
@Hera-han

**Comment by dujiwei** [comment]
队名：鹏图
项目名：碳中合下基于“图计算”的“电网设备一张图”
项目介绍：用知识图谱构建一张电网设备图，从家用智能电表，到小变电站，到输送电网等。完成电网设备一张图建设，对沿途设备容量，节点电压，电网断面等进行监控展示。

成员
@tellixu
@大猫
@小可
@dujiwei

**Comment by dujiwei** [comment]
> 队名：鹏图 项目名：碳中合下基于“图计算”的“电网设备一张图” 项目介绍：用知识图谱构建一张电网设备图，从家用智能电表，到小变电站，到输送电网等。完成电网设备一张图建设，对沿途设备容量，节点电压，电网断面等进行监控展示。
> 
> 成员 @tellixu @大猫 @小可 @dujiwei

加油

**Comment by goranc** [comment]
Team : **Dinamo**
Members : @https://github.com/goranc ```Goran Cvijanovic```, @https://github.com/mirac7 ```Mirano Tuk``` 

Project : **GraphYourCodeVulnerability**
Introduction : Validation of GitHub projects exposure to CVE vulnerabilities

**_Description_** :
These days when log4j vulnerability [CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)  exposes many Java servers to the possible exploration by malicious individuals, you as maintainer of the code or the information system is asking yourself :
> Is my code vulnerable to that threat ? 

> Do I have somewhere in my software stack that log4j peace of code ? 

Well you definitely **have to check** if that is true, because you don’t want to be exposed and become a victim of some _Ransomware_ or other malicious threats and actors.
But hey I’m using that code from GitHub repository. Can I check somehow if that repo is vulnerable to this log4j threat, or any other known threat ?
[ **Yes  you will  !!** ](), when we finish this Nebula Hackathon and give to the world powerful solution to verify exposure of your code in GitHub repository to known threats. You will even be able to search and pivot by code library name and find correlated repositories with **exposure to common vulnerabilities** known as **CVE**s.

**_Design_** :
Project will be developed in python and deployed as a web application with Nebula Graph as a backend database.
```
- Custom python code for web application service
- Nginx web server
- Nebula Graph database integrated with Elasticsearch engine
- Javascript visualization library
```
**_Testing_** :
Project will be deployed on a publicly available application server behind Nginx reverse proxy. 
Data set will have already populated graph objects for most popular GitHub repositories, for more than 32000 repositories. 
Users can select any of them and check vulnerability status of all components included in visually attractive graph representation supported with full-text search option. 
For testing we will examine vulnerabilities for [Nebula Repository](https://github.com/vesoft-inc/nebula)

**Comment by whitewum** [comment]
项目名：悬挂边和超级节点
项目介绍：改造的存储结构，避免悬挂边的产生；提供功能判断是否是超级节点，提供功能快速得到出入度；另外加速图拓扑的访问。设计可以兼容升级。


成员
@panda-sheep 
@whitewum

**Comment by phpgodfather** [comment]
> 队名：NullReferenceException 项目名：nebula-net & nebula-php 项目介绍：从现在开始，我们可以从.NET和PHP中导入Nebula Graph 团队成员： @heyanlong —— Apache Software Foundation / Apache SkyWalking committer @shyboylpf —— Xignite / Market data delivery
> 
> Team name: NullReferenceException Project name: nebula-net & nebula-php Project introduction: From now on, we can import Nebula Graph in .NET & PHP. Team members: @heyanlong —— Apache Software Foundation / Apache SkyWalking committer @shyboylpf —— Xignite / Market data delivery
真好

**Comment by heyanlong** [comment]
@phpgodfather 谢谢支持。
